name: Issue Created Bot

on:
  workflow_dispatch:

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Run bot script
      run: |
        go run main.go